/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package ahorcado.parte1.ui;

import ahorcado.parte1.model.HangMan;
import controller.HangManController;
import javax.swing.Icon;
import javax.swing.ImageIcon;
import javax.swing.JDialog;
import javax.swing.JOptionPane;

/**
 *
 * @author daw1al11
 */
public class MainWindow extends javax.swing.JFrame {

    Icon[] imagenes = new Icon[6];

    public void iconInicializer() {
        for (int i = 0; i < imagenes.length; i++) {
            imagenes[i] = new javax.swing.ImageIcon(getClass().getResource("/ahorcado/parte1/hangmanimages/Hangman-" + i + ".png"));
        }
    }

    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(MainWindow.class.getName());

    /**
     * Creates new form MainWindow
     */
//    public MainWindow() {
//        initComponents();
//        iconInicializer();
//
//    }
    private HangManController myController;
    private HangMan hangMan;
    public MainWindow(HangManController controller) {
        myController = controller;

    }
    public void startNewGame(){
                Object seleccion = JOptionPane.showInputDialog(
                this,
                "Modo de xogo",
                "Selecciona un modo de xogo",
                JOptionPane.QUESTION_MESSAGE,
                null, // null para icono defecto
                new Object[]{"Clásico", "Competitivo"},
                "");
    }
    public void init() {

        initComponents();
        iconInicializer();

        this.setVisible(true);
        startNewGame();


    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        jPanelN = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanelS = new javax.swing.JPanel();
        jPanel5 = new javax.swing.JPanel();
        jBNovaPartida = new javax.swing.JButton();
        jBExit = new javax.swing.JButton();
        jPanelW = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        JLhiddenWordTx = new javax.swing.JLabel();
        jLfailLettersTx = new javax.swing.JLabel();
        jLintLetterTx = new javax.swing.JLabel();
        jLhiddenWordOut = new javax.swing.JLabel();
        jLfailLetterOut = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jTextField1 = new javax.swing.JTextField();
        jPanelE = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        jLImage_Ahorcado = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(600, 400));

        jPanelN.setLayout(new java.awt.BorderLayout());

        jPanel3.setMinimumSize(new java.awt.Dimension(44, 50));
        jPanel3.setPreferredSize(new java.awt.Dimension(44, 50));
        jPanel3.setLayout(new java.awt.GridBagLayout());

        jLabel1.setFont(new java.awt.Font("Liberation Sans", 0, 24)); // NOI18N
        jLabel1.setText("O Xogo do Aforcado");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.insets = new java.awt.Insets(20, 0, 0, 0);
        jPanel3.add(jLabel1, gridBagConstraints);

        jPanelN.add(jPanel3, java.awt.BorderLayout.CENTER);

        getContentPane().add(jPanelN, java.awt.BorderLayout.NORTH);

        jPanelS.setLayout(new java.awt.BorderLayout());

        jPanel5.setLayout(new java.awt.GridBagLayout());

        jBNovaPartida.setText("Nova Partida");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.insets = new java.awt.Insets(0, 0, 20, 5);
        jPanel5.add(jBNovaPartida, gridBagConstraints);

        jBExit.setText("Exit");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.insets = new java.awt.Insets(0, 5, 20, 0);
        jPanel5.add(jBExit, gridBagConstraints);

        jPanelS.add(jPanel5, java.awt.BorderLayout.CENTER);

        getContentPane().add(jPanelS, java.awt.BorderLayout.SOUTH);

        jPanelW.setLayout(new java.awt.BorderLayout());

        jPanel2.setMinimumSize(new java.awt.Dimension(300, 62));
        jPanel2.setPreferredSize(new java.awt.Dimension(300, 62));
        jPanel2.setLayout(new java.awt.GridBagLayout());

        JLhiddenWordTx.setText("Palabra a adiviñar :");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
        gridBagConstraints.insets = new java.awt.Insets(2, 20, 2, 0);
        jPanel2.add(JLhiddenWordTx, gridBagConstraints);

        jLfailLettersTx.setText("Letras falladas :");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
        gridBagConstraints.insets = new java.awt.Insets(2, 20, 2, 0);
        jPanel2.add(jLfailLettersTx, gridBagConstraints);

        jLintLetterTx.setText("Introduce unha letra : ");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
        gridBagConstraints.insets = new java.awt.Insets(0, 20, 0, 0);
        jPanel2.add(jLintLetterTx, gridBagConstraints);

        jLhiddenWordOut.setName(""); // NOI18N
        jPanel2.add(jLhiddenWordOut, new java.awt.GridBagConstraints());
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 1;
        jPanel2.add(jLfailLetterOut, gridBagConstraints);

        jButton1.setText("Probar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 2;
        jPanel2.add(jButton1, gridBagConstraints);

        jTextField1.setMinimumSize(new java.awt.Dimension(80, 30));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.gridwidth = java.awt.GridBagConstraints.RELATIVE;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 2.0;
        jPanel2.add(jTextField1, gridBagConstraints);

        jPanelW.add(jPanel2, java.awt.BorderLayout.CENTER);

        getContentPane().add(jPanelW, java.awt.BorderLayout.WEST);

        jPanelE.setLayout(new java.awt.BorderLayout());

        jPanel4.setLayout(new java.awt.GridLayout(1, 0));

        jLImage_Ahorcado.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ahorcado/parte1/hangmanimages/Hangman-0.png"))); // NOI18N
        jPanel4.add(jLImage_Ahorcado);

        jPanelE.add(jPanel4, java.awt.BorderLayout.CENTER);

        getContentPane().add(jPanelE, java.awt.BorderLayout.EAST);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // Nota que usamos "/" en lugar de "\\" y empezamos desde la raíz del paquete
        this.jLImage_Ahorcado.setIcon(imagenes[4]);
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
//        java.awt.EventQueue.invokeLater(() -> new MainWindow().setVisible(true));
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {

                HangManController myController = new HangManController();
                new MainWindow(myController);

            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel JLhiddenWordTx;
    private javax.swing.JButton jBExit;
    private javax.swing.JButton jBNovaPartida;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLImage_Ahorcado;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLfailLetterOut;
    private javax.swing.JLabel jLfailLettersTx;
    private javax.swing.JLabel jLhiddenWordOut;
    private javax.swing.JLabel jLintLetterTx;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanelE;
    private javax.swing.JPanel jPanelN;
    private javax.swing.JPanel jPanelS;
    private javax.swing.JPanel jPanelW;
    private javax.swing.JTextField jTextField1;
    // End of variables declaration//GEN-END:variables
}
